sudo: required
services:
  - docker
language: python

env:
  global:
    - COMPOSE_FILE=.travis.docker-compose.yml
    - COMMIT=${TRAVIS_COMMIT::7}

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
  - docker build -t $DOCKER_REPO:latest .

before_script:
  - docker-compose up -d postgres redis
  - sleep 5  # Postgres needs a few seconds to start and Django hard crashes without it

script:
  - true

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $DOCKER_REPO:latest $DOCKER_REPO:$COMMIT
  - docker tag $DOCKER_REPO:latest $DOCKER_REPO:$TAG
  - docker push $DOCKER_REPO:$COMMIT
  - docker push $DOCKER_REPO:$TAG
